name: flutter_prime_wave_task
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  dio: ^5.8.0+1
  dartz: ^0.10.1
  flutter_dotenv: ^5.2.1
  bloc: ^9.0.1
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  pretty_dio_logger: ^1.4.0
  retry: ^3.1.2
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator:
  build_runner:
  auto_route_generator:


flutter:
  uses-material-design: true

  assets:
    - .env








